version: '3.9'

services:
  node-app:
    container_name: node-app
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secretMongo7760

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secretMongo7760
      ME_CONFIG_MONGODB_URL: mongodb://root:db@mongo:27017/
